options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

steps:
  # Build the Streamlit application container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/fulfillment-mixy-matchi:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/fulfillment-mixy-matchi:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fulfillment-mixy-matchi:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fulfillment-mixy-matchi:latest']

images:
  - 'gcr.io/$PROJECT_ID/fulfillment-mixy-matchi:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/fulfillment-mixy-matchi:latest'

timeout: '3600s'
